// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nheejysbqyliaphbyalv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oZWVqeXNicXlsaWFwaGJ5YWx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NjQ5ODEsImV4cCI6MjA1NzQ0MDk4MX0.1C4zVhHlxHal877jgRGUzxyU6U2XVidFzUwFyJwPu40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);